from enum import Enum

class Opciones(Enum):
    CAMBIAR_CREDENCIALES = "CAMBIAR_CREDENCIALES"
    MODIFICAR_CRITERIOS = "MODIFICAR_CRITERIOS"
    ELIMINAR_CORREOS = "ELIMINAR_CORREOS"
    MARCAR_COMO_SPAM = "MARCAR_COMO_SPAM"
    SALIR = "SALIR"
    AGREGAR_PALABRA = "AGREGAR_PALABRA"
    ELIMINAR_PALABRA = "ELIMINAR_PALABRA"
    AGREGAR_REMITENTE = "AGREGAR_REMITENTE"
    ELIMINAR_REMITENTE = "ELIMINAR_REMITENTE"
    ELIMINAR_TODOS_FILTROS = "ELIMINAR_TODOS_FILTROS"
    ATRAS = "ATRAS"
    